[package]
name = "fcb_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "_fcb"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
fcb_core = { workspace = true }
cjseq = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ordered-float = { workspace = true }
chrono = { workspace = true }
pyo3-asyncio = { version = "0.20", features = [
  "tokio-runtime",
], optional = true }
tokio = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }


[features]
default = ["http"]
http = ["fcb_core/http", "tokio", "reqwest", "pyo3-asyncio"]

[build-dependencies]
pyo3-build-config = "0.20"
