# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatCityBuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Header(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Header()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Header
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Header
    def Transform(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Header
    def Columns(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Column()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Header
    def ColumnsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Header
    def ColumnsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Header
    def FeaturesCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Header
    def GeographicalExtent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = GeographicalExtent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Header
    def ReferenceSystem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ReferenceSystem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Header
    def Identifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def ReferenceDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocContactName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocContactType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocRole(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocPhone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocEmail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocWebsite(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocAddressThoroughfareNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocAddressThoroughfareName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocAddressLocality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocAddressPostcode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PocAddressCountry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def Attributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Header
    def AttributesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Header
    def AttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Header
    def AttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

def HeaderStart(builder):
    builder.StartObject(20)

def Start(builder):
    HeaderStart(builder)

def HeaderAddTransform(builder, transform):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(transform), 0)

def AddTransform(builder, transform):
    HeaderAddTransform(builder, transform)

def HeaderAddColumns(builder, columns):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(columns), 0)

def AddColumns(builder, columns):
    HeaderAddColumns(builder, columns)

def HeaderStartColumnsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartColumnsVector(builder, numElems):
    return HeaderStartColumnsVector(builder, numElems)

def HeaderAddFeaturesCount(builder, featuresCount):
    builder.PrependUint64Slot(2, featuresCount, 0)

def AddFeaturesCount(builder, featuresCount):
    HeaderAddFeaturesCount(builder, featuresCount)

def HeaderAddGeographicalExtent(builder, geographicalExtent):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(geographicalExtent), 0)

def AddGeographicalExtent(builder, geographicalExtent):
    HeaderAddGeographicalExtent(builder, geographicalExtent)

def HeaderAddReferenceSystem(builder, referenceSystem):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(referenceSystem), 0)

def AddReferenceSystem(builder, referenceSystem):
    HeaderAddReferenceSystem(builder, referenceSystem)

def HeaderAddIdentifier(builder, identifier):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(identifier), 0)

def AddIdentifier(builder, identifier):
    HeaderAddIdentifier(builder, identifier)

def HeaderAddReferenceDate(builder, referenceDate):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(referenceDate), 0)

def AddReferenceDate(builder, referenceDate):
    HeaderAddReferenceDate(builder, referenceDate)

def HeaderAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    HeaderAddTitle(builder, title)

def HeaderAddPocContactName(builder, pocContactName):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(pocContactName), 0)

def AddPocContactName(builder, pocContactName):
    HeaderAddPocContactName(builder, pocContactName)

def HeaderAddPocContactType(builder, pocContactType):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(pocContactType), 0)

def AddPocContactType(builder, pocContactType):
    HeaderAddPocContactType(builder, pocContactType)

def HeaderAddPocRole(builder, pocRole):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(pocRole), 0)

def AddPocRole(builder, pocRole):
    HeaderAddPocRole(builder, pocRole)

def HeaderAddPocPhone(builder, pocPhone):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(pocPhone), 0)

def AddPocPhone(builder, pocPhone):
    HeaderAddPocPhone(builder, pocPhone)

def HeaderAddPocEmail(builder, pocEmail):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(pocEmail), 0)

def AddPocEmail(builder, pocEmail):
    HeaderAddPocEmail(builder, pocEmail)

def HeaderAddPocWebsite(builder, pocWebsite):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(pocWebsite), 0)

def AddPocWebsite(builder, pocWebsite):
    HeaderAddPocWebsite(builder, pocWebsite)

def HeaderAddPocAddressThoroughfareNumber(builder, pocAddressThoroughfareNumber):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(pocAddressThoroughfareNumber), 0)

def AddPocAddressThoroughfareNumber(builder, pocAddressThoroughfareNumber):
    HeaderAddPocAddressThoroughfareNumber(builder, pocAddressThoroughfareNumber)

def HeaderAddPocAddressThoroughfareName(builder, pocAddressThoroughfareName):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(pocAddressThoroughfareName), 0)

def AddPocAddressThoroughfareName(builder, pocAddressThoroughfareName):
    HeaderAddPocAddressThoroughfareName(builder, pocAddressThoroughfareName)

def HeaderAddPocAddressLocality(builder, pocAddressLocality):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(pocAddressLocality), 0)

def AddPocAddressLocality(builder, pocAddressLocality):
    HeaderAddPocAddressLocality(builder, pocAddressLocality)

def HeaderAddPocAddressPostcode(builder, pocAddressPostcode):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(pocAddressPostcode), 0)

def AddPocAddressPostcode(builder, pocAddressPostcode):
    HeaderAddPocAddressPostcode(builder, pocAddressPostcode)

def HeaderAddPocAddressCountry(builder, pocAddressCountry):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(pocAddressCountry), 0)

def AddPocAddressCountry(builder, pocAddressCountry):
    HeaderAddPocAddressCountry(builder, pocAddressCountry)

def HeaderAddAttributes(builder, attributes):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(attributes), 0)

def AddAttributes(builder, attributes):
    HeaderAddAttributes(builder, attributes)

def HeaderStartAttributesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartAttributesVector(builder, numElems):
    return HeaderStartAttributesVector(builder, numElems)

def HeaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeaderEnd(builder)
