/*
 * 3DBAG API
 *
 * The [3DBAG](https://3dbag.nl) is an up-to-date dataset containing 3D building models of the Netherlands.  The 3DBAG is open data. It contains 3D models at multiple levels of detail,  which are generated by combining two open data sets:  the building data from the BAG and the height data from the AHN.  The 3DBAG is updated regularly, keeping it up-to-date with the latest openly  available building stock and elevation information.  The 3DBAG is maintained by the 3D geoinformation group and 3DGI.  Copyright (c) 2023 TU Delft 3D geoinformation group, Ravi Peters (3DGI), and Balázs Dukai (3DGI)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@3dbag.nl
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    /// identifier of the collection used, for example, in URIs
    #[serde(rename = "id")]
    pub id: String,
    /// human readable title of the collection
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// a description of the features in the collection
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "links")]
    pub links: Vec<models::Link>,
    #[serde(rename = "extent", skip_serializing_if = "Option::is_none")]
    pub extent: Option<models::Extent>,
    /// indicator about the type of the items in the collection (the default value is 'feature').
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    /// the list of coordinate reference systems supported by the service
    #[serde(rename = "crs", skip_serializing_if = "Option::is_none")]
    pub crs: Option<Vec<String>>,
}

impl Collection {
    pub fn new(id: String, links: Vec<models::Link>) -> Collection {
        Collection {
            id,
            title: None,
            description: None,
            links,
            extent: None,
            item_type: None,
            crs: None,
        }
    }
}
