/*
 * 3DBAG API
 *
 * The [3DBAG](https://3dbag.nl) is an up-to-date dataset containing 3D building models of the Netherlands.  The 3DBAG is open data. It contains 3D models at multiple levels of detail,  which are generated by combining two open data sets:  the building data from the BAG and the height data from the AHN.  The 3DBAG is updated regularly, keeping it up-to-date with the latest openly  available building stock and elevation information.  The 3DBAG is maintained by the 3D geoinformation group and 3DGI.  Copyright (c) 2023 TU Delft 3D geoinformation group, Ravi Peters (3DGI), and Balázs Dukai (3DGI)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@3dbag.nl
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Extent : The extent of the features in the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other extents, for example, thermal or pressure ranges.  An array of extents is provided for each extent type (spatial, temporal). The first item in the array describes the overall extent of the data. All subsequent items describe more precise extents, e.g., to identify clusters of data. Clients only interested in the overall extent will only need to access the first extent in the array.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Extent {
    #[serde(rename = "spatial", skip_serializing_if = "Option::is_none")]
    pub spatial: Option<models::ExtentSpatial>,
}

impl Extent {
    /// The extent of the features in the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other extents, for example, thermal or pressure ranges.  An array of extents is provided for each extent type (spatial, temporal). The first item in the array describes the overall extent of the data. All subsequent items describe more precise extents, e.g., to identify clusters of data. Clients only interested in the overall extent will only need to access the first extent in the array.
    pub fn new() -> Extent {
        Extent { spatial: None }
    }
}
