/*
 * 3DBAG API
 *
 * The [3DBAG](https://3dbag.nl) is an up-to-date dataset containing 3D building models of the Netherlands.  The 3DBAG is open data. It contains 3D models at multiple levels of detail,  which are generated by combining two open data sets:  the building data from the BAG and the height data from the AHN.  The 3DBAG is updated regularly, keeping it up-to-date with the latest openly  available building stock and elevation information.  The 3DBAG is maintained by the 3D geoinformation group and 3DGI.  Copyright (c) 2023 TU Delft 3D geoinformation group, Ravi Peters (3DGI), and Balázs Dukai (3DGI)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@3dbag.nl
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExtentSpatial : The spatial extent of the features in the collection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtentSpatial {
    /// One or more bounding boxes that describe the spatial extent of the dataset. In the Core only a single bounding box is supported.  Extensions may support additional areas. The first bounding box describes the overall spatial extent of the data. All subsequent bounding boxes describe more precise bounding boxes, e.g., to identify clusters of data. Clients only interested in the overall spatial extent will only need to access the first bounding box in the array.
    #[serde(rename = "bbox", skip_serializing_if = "Option::is_none")]
    pub bbox: Option<Vec<Vec<f64>>>,
    /// Coordinate reference system of the returned coordinates.  Currently only `https://www.opengis.net/def/crs/EPSG/0/7415` is supported.
    #[serde(rename = "crs", skip_serializing_if = "Option::is_none")]
    pub crs: Option<Crs>,
}

impl ExtentSpatial {
    /// The spatial extent of the features in the collection.
    pub fn new() -> ExtentSpatial {
        ExtentSpatial {
            bbox: None,
            crs: None,
        }
    }
}
/// Coordinate reference system of the returned coordinates.  Currently only `https://www.opengis.net/def/crs/EPSG/0/7415` is supported.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Crs {
    #[serde(rename = "https://www.opengis.net/def/crs/EPSG/0/7415")]
    #[default]
    HttpsColonSlashSlashWwwPeriodOpengisPeriodNetSlashDefSlashCrsSlashEpsgSlash0Slash7415,
}
