/*
 * 3DBAG API
 *
 * The [3DBAG](https://3dbag.nl) is an up-to-date dataset containing 3D building models of the Netherlands.  The 3DBAG is open data. It contains 3D models at multiple levels of detail,  which are generated by combining two open data sets:  the building data from the BAG and the height data from the AHN.  The 3DBAG is updated regularly, keeping it up-to-date with the latest openly  available building stock and elevation information.  The 3DBAG is maintained by the 3D geoinformation group and 3DGI.  Copyright (c) 2023 TU Delft 3D geoinformation group, Ravi Peters (3DGI), and Balázs Dukai (3DGI)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@3dbag.nl
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureCollection {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "features")]
    pub features: Vec<models::FeatureCityJson>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::Link>>,
    #[serde(rename = "timeStamp", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<String>,
    #[serde(rename = "numberMatched", skip_serializing_if = "Option::is_none")]
    pub number_matched: Option<i32>,
    #[serde(rename = "numberReturned", skip_serializing_if = "Option::is_none")]
    pub number_returned: Option<i32>,
}

impl FeatureCollection {
    pub fn new(r#type: Type, features: Vec<models::FeatureCityJson>) -> FeatureCollection {
        FeatureCollection {
            r#type,
            features,
            links: None,
            time_stamp: None,
            number_matched: None,
            number_returned: None,
        }
    }
}
///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "FeatureCollection")]
    #[default]
    FeatureCollection,
}
