use axum::{
    extract::{Path, Query as AxumQuery, State},
    http::StatusCode,
    response::Json,
};
use chrono::Utc;
use cjseq::CityJSONFeature;
use fcb_core::packed_rtree::Query;
use fcb_core::{FixedStringKey, HttpFcbReader, KeyType, Operator};
use http_range_client::AsyncHttpRangeClient;
use serde::Deserialize;
use std::sync::Arc;
use tracing::{info, warn};

use crate::models::*;
use crate::AppState;

#[derive(Debug, Deserialize)]
pub struct CollectionQuery {
    pub f: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct BboxQuery {
    limit: Option<i32>,
    offset: Option<i32>,
    bbox: Option<String>,
    crs: Option<String>,
    bbox_crs: Option<String>,
}

pub async fn landing_page(
    State(_state): State<Arc<AppState>>,
) -> Result<Json<LandingPage>, StatusCode> {
    info!("Serving landing page");

    let landing_page = LandingPage {
        title: Some("3DBAG API".to_string()),
        description: Some(
            concat!(
            "The 3DBAG is an up-to-date dataset containing 3D building models of the Netherlands. ",
            "The 3DBAG is open data. It contains 3D models at multiple levels of detail, ",
            "which are generated by combining two open data sets: ",
            "the building data from the BAG and the height data from the AHN. ",
            "The 3DBAG is updated regularly, keeping it up-to-date with the latest openly ",
            "available building stock and elevation information."
        )
            .to_string(),
        ),
        links: vec![
            Link {
                href: "/".to_string(),
                rel: "self".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("Landing page".to_string()),
                ..Default::default()
            },
            Link {
                href: "https://docs.3dbag.nl/en/".to_string(),
                rel: "service-doc".to_string(),
                r#type: Some("text/html".to_string()),
                title: Some("3DBAG documentation".to_string()),
                ..Default::default()
            },
            Link {
                href: "/conformance".to_string(),
                rel: "conformance".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("Conformance declaration".to_string()),
                ..Default::default()
            },
            Link {
                href: "/collections".to_string(),
                rel: "data".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("Collections".to_string()),
                ..Default::default()
            },
        ],
    };

    Ok(Json(landing_page))
}

pub async fn conformance() -> Result<Json<ConfClasses>, StatusCode> {
    info!("Serving conformance declaration");

    let conformance = ConfClasses {
        conforms_to: vec!["https://cityjson.org/specs/1.1.1/".to_string()],
    };

    Ok(Json(conformance))
}

pub async fn collections(
    State(_state): State<Arc<AppState>>,
) -> Result<Json<Collections>, StatusCode> {
    info!("Serving collections");

    let pand_collection = Collection {
        id: "pand".to_string(),
        title: Some("BAG building models".to_string()),
        description: Some(concat!(
            "LOD1.2, LOD1.3 and LOD2.2 3D building models of all buildings in the Netherlands. ",
            "Generated by combining the building data from the BAG with the height data from the AHN. ",
            "The 3D building models are available in multiple formats."
        ).to_string()),
        links: vec![
            Link {
                href: "/collections/pand".to_string(),
                rel: "self".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("This collection".to_string()),
                ..Default::default()
            },
            Link {
                href: "/collections/pand/items".to_string(),
                rel: "items".to_string(),
                r#type: Some("application/city+json".to_string()),
                title: Some("Building models".to_string()),
                ..Default::default()
            },
            Link {
                href: "https://creativecommons.org/licenses/by/4.0/".to_string(),
                rel: "license".to_string(),
                r#type: Some("text/html".to_string()),
                title: Some("CC BY 4.0".to_string()),
                ..Default::default()
            },
        ],
        extent: Some(Extent {
            spatial: Some(ExtentSpatial {
                bbox: Some(vec![vec![3.37087, 50.7539, 7.21097, 53.4658]]),
                crs: Some(Crs::default()),
            }),
        }),
        item_type: Some("feature".to_string()),
        crs: Some(vec![
            "http://www.opengis.net/def/crs/OGC/1.3/CRS84".to_string(),
            "http://www.opengis.net/def/crs/EPSG/0/28992".to_string(),
        ]),
    };

    let collections = Collections {
        links: vec![Link {
            href: "/collections".to_string(),
            rel: "self".to_string(),
            r#type: Some("application/json".to_string()),
            title: Some("Collections".to_string()),
            ..Default::default()
        }],
        collections: vec![pand_collection],
    };

    Ok(Json(collections))
}

pub async fn collection_by_id(
    Path(collection_id): Path<String>,
    State(_state): State<Arc<AppState>>,
) -> Result<Json<Collection>, StatusCode> {
    info!("Serving collection: {}", collection_id);

    if collection_id != "pand" {
        return Err(StatusCode::NOT_FOUND);
    }

    let collection = Collection {
        id: "pand".to_string(),
        title: Some("BAG building models".to_string()),
        description: Some(concat!(
            "LOD1.2, LOD1.3 and LOD2.2 3D building models of all buildings in the Netherlands. ",
            "Generated by combining the building data from the BAG with the height data from the AHN. ",
            "The 3D building models are available in multiple formats."
        ).to_string()),
        links: vec![
            Link {
                href: "/collections/pand".to_string(),
                rel: "self".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("This collection".to_string()),
                ..Default::default()
            },
            Link {
                href: "/collections/pand/items".to_string(),
                rel: "items".to_string(),
                r#type: Some("application/city+json".to_string()),
                title: Some("Building models".to_string()),
                ..Default::default()
            },
            Link {
                href: "https://creativecommons.org/licenses/by/4.0/".to_string(),
                rel: "license".to_string(),
                r#type: Some("text/html".to_string()),
                title: Some("CC BY 4.0".to_string()),
                ..Default::default()
            },
        ],
        extent: Some(Extent {
            spatial: Some(ExtentSpatial {
                bbox: Some(vec![vec![3.37087, 50.7539, 7.21097, 53.4658]]), // TODO: get from FCB
                crs: Some(Crs::default()),
            }),
        }),
        item_type: Some("feature".to_string()),
        crs: Some(vec![
            "http://www.opengis.net/def/crs/OGC/1.3/CRS84".to_string(),
            "http://www.opengis.net/def/crs/EPSG/0/28992".to_string(),
        ]),
    };

    Ok(Json(collection))
}

pub async fn collection_items(
    Path(collection_id): Path<String>,
    AxumQuery(query): AxumQuery<BboxQuery>,
    State(state): State<Arc<AppState>>,
) -> Result<Json<FeatureCollection>, StatusCode> {
    info!(
        "Serving items for collection: {} with query: {:?}",
        collection_id, query
    );

    if collection_id != "pand" {
        return Err(StatusCode::NOT_FOUND);
    }

    let limit = query
        .limit
        .unwrap_or(state.max_return_features as i32)
        .min(state.max_return_features as i32);

    let bbox = query.bbox.as_ref().map(|bbox_str| {
        let parts: Result<Vec<f64>, _> = bbox_str
            .split(',')
            .map(|s| s.trim().parse::<f64>())
            .collect();
        
        match parts {
            Ok(coords) => {
                if coords.len() == 4 {
                    Ok(coords)
                } else if coords.len() == 6 {
                    Ok(vec![coords[0], coords[1], coords[3], coords[4]])
                } else {
                    Err(StatusCode::BAD_REQUEST)
                }
            }
            Err(_) => Err(StatusCode::BAD_REQUEST),
        }
    });

    let bbox = match bbox {
        Some(Ok(bbox)) => Some(bbox),
        Some(Err(e)) => {
            warn!("Failed to parse bbox: {:?}", e);
            return Err(StatusCode::BAD_REQUEST);
        }
        None => None,
    };
    let http_reader = match HttpFcbReader::open(&state.fcb_url).await {
        Ok(reader) => reader,
        Err(e) => {
            warn!("Failed to open FCB reader: {:?}", e);
            return Err(StatusCode::INTERNAL_SERVER_ERROR);
        }
    };

    // Apply bbox filtering if provided

    let features = if let Some(bbox) = &bbox {
        fetch_features_by_bbox(http_reader, bbox, limit).await
    } else {
        fetch_features_limited(http_reader, limit as u32).await
    };

    let features = match features {
        Ok(features) => features,
        Err(e) => {
            warn!("Failed to fetch features: {:?}", e);
            return Err(StatusCode::INTERNAL_SERVER_ERROR);
        }
    };

    let features_count = features.len() as i64;

    let feature_collection = FeatureCollection {
        r#type: Type::FeatureCollection,
        features: features
            .into_iter()
            .map(|f| FeatureCityJson {
                feature: Some(serde_json::to_value(f.clone()).unwrap_or_default()),
                id: Some(f.id.clone()),
                links: Some(vec![
                    Link {
                        href: format!("/collections/{}/items/{}", collection_id, f.id),
                        rel: "self".to_string(),
                        r#type: Some("application/city+json".to_string()),
                        title: Some("this document".to_string()),
                        ..Default::default()
                    },
                    Link {
                        href: format!("/collections/{}", collection_id),
                        rel: "collection".to_string(),
                        r#type: Some("application/json".to_string()),
                        title: Some("Collection".to_string()),
                        ..Default::default()
                    },
                ]),
                ..Default::default()
            })
            .collect(),
        number_matched: Some(features_count as i32),
        number_returned: Some(features_count as i32),
        time_stamp: Some(Utc::now().to_rfc3339()),
        links: Some(vec![Link {
            href: format!("/collections/{}/items", collection_id),
            rel: "self".to_string(),
            r#type: Some("application/json".to_string()),
            title: Some("this document".to_string()),
            ..Default::default()
        }]),
    };

    Ok(Json(feature_collection))
}

pub async fn collection_item_by_id(
    Path((collection_id, item_id)): Path<(String, String)>,
    State(state): State<Arc<AppState>>,
) -> Result<Json<FeatureCityJson>, StatusCode> {
    info!(
        "Serving item: {} from collection: {}",
        item_id, collection_id
    );

    if collection_id != "pand" {
        return Err(StatusCode::NOT_FOUND);
    }

    let http_reader = match HttpFcbReader::open(&state.fcb_url).await {
        Ok(reader) => reader,
        Err(e) => {
            warn!("Failed to open FCB reader: {:?}", e);
            return Err(StatusCode::INTERNAL_SERVER_ERROR);
        }
    };

    let feature = fetch_feature_by_id(http_reader, &item_id).await;

    let feature = feature.map(|f| FeatureCityJson {
        feature: f.map(|f| serde_json::to_value(f).unwrap_or_default()),
        id: Some(item_id.clone()),
        links: Some(vec![
            Link {
                href: format!("/collections/{}/items/{}", collection_id, item_id),
                rel: "self".to_string(),
                r#type: Some("application/json".to_string()),
                title: Some("this document".to_string()),
                ..Default::default()
            },
            Link {
                href: format!("/collections/{}", collection_id),
                rel: "collection".to_string(),
                r#type: Some("application/json".to_string()),
                ..Default::default()
            },
            Link {
                href: format!("/collections/{}/items", collection_id),
                rel: "parent".to_string(),
                r#type: Some("application/city+json".to_string()),
                ..Default::default()
            },
        ]),
    });

    match feature {
        Ok(feature) => Ok(Json(feature)),
        Err(e) => {
            warn!("Failed to fetch feature by ID: {:?}", e);
            Err(StatusCode::NOT_FOUND)
        }
    }
}

async fn fetch_features_by_bbox<T: AsyncHttpRangeClient + Send + Sync>(
    reader: HttpFcbReader<T>,
    bbox: &Vec<f64>,
    limit: i32,
) -> Result<Vec<CityJSONFeature>, anyhow::Error> {
    let (minx, miny, maxx, maxy) = (bbox[0], bbox[1], bbox[2], bbox[3]);

    let mut iter = reader
        .select_query(Query::BBox(minx, miny, maxx, maxy))
        .await?;

    let mut features = Vec::new();
    let mut count = 0;

    while count < limit {
        match iter.next().await? {
            Some(feature_result) => {
                features.push(feature_result.cj_feature()?);
                count += 1;
            }
            None => break,
        }
    }

    Ok(features)
}

async fn fetch_features_limited<T: AsyncHttpRangeClient + Send + Sync>(
    reader: HttpFcbReader<T>,
    limit: u32,
) -> Result<Vec<CityJSONFeature>, anyhow::Error> {
    let mut iter = reader.select_all().await?;

    let mut features = Vec::new();
    let mut count = 0;

    while count < limit {
        match iter.next().await? {
            Some(feature_result) => {
                features.push(feature_result.cj_feature()?);
                count += 1;
            }
            None => break,
        }
    }

    Ok(features)
}

async fn fetch_feature_by_id<T: AsyncHttpRangeClient + Send + Sync>(
    reader: HttpFcbReader<T>,
    feature_id: &str,
) -> Result<Option<CityJSONFeature>, anyhow::Error> {
    let query: Vec<(String, Operator, KeyType)> = vec![(
        "identificatie".to_string(),
        Operator::Eq,
        KeyType::StringKey50(FixedStringKey::from_str(feature_id)),
    )];

    let mut iter = reader.select_attr_query(&query).await?;

    if let Some(feature_result) = iter.next().await? {
        return Ok(Some(feature_result.cj_feature()?));
    }

    Ok(None)
}
