[package]
name = "fcb_cpp"
version = "0.7.6"
edition = "2021"
authors = ["Hidemichi Baba <baba.papa1120.ba@gmail.com>"]
license = "MIT"
description = "C++ bindings for FlatCityBuf core library"

[lib]
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
fcb_core = { workspace = true, default-features = false }
cxx = { workspace = true }
cjseq = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
cxx-build = { workspace = true }
