// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CityObjectType {
  Bridge = 0,
  BridgePart = 1,
  BridgeInstallation = 2,
  BridgeConstructiveElement = 3,
  BridgeRoom = 4,
  BridgeFurniture = 5,
  Building = 6,
  BuildingPart = 7,
  BuildingInstallation = 8,
  BuildingConstructiveElement = 9,
  BuildingFurniture = 10,
  BuildingStorey = 11,
  BuildingRoom = 12,
  BuildingUnit = 13,
  CityFurniture = 14,
  CityObjectGroup = 15,
  GenericCityObject = 16,
  LandUse = 17,
  OtherConstruction = 18,
  PlantCover = 19,
  SolitaryVegetationObject = 20,
  TINRelief = 21,
  Road = 22,
  Railway = 23,
  Waterway = 24,
  TransportSquare = 25,
  Tunnel = 26,
  TunnelPart = 27,
  TunnelInstallation = 28,
  TunnelConstructiveElement = 29,
  TunnelHollowSpace = 30,
  TunnelFurniture = 31,
  WaterBody = 32
}
