// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vector } from '../flat-city-buf/vector.js';


export class Transform {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Transform {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

scale(obj?:Vector):Vector|null {
  return (obj || new Vector()).__init(this.bb_pos, this.bb!);
}

translate(obj?:Vector):Vector|null {
  return (obj || new Vector()).__init(this.bb_pos + 24, this.bb!);
}

static sizeOf():number {
  return 48;
}

static createTransform(builder:flatbuffers.Builder, scale_x: number, scale_y: number, scale_z: number, translate_x: number, translate_y: number, translate_z: number):flatbuffers.Offset {
  builder.prep(8, 48);
  builder.prep(8, 24);
  builder.writeFloat64(translate_z);
  builder.writeFloat64(translate_y);
  builder.writeFloat64(translate_x);
  builder.prep(8, 24);
  builder.writeFloat64(scale_z);
  builder.writeFloat64(scale_y);
  builder.writeFloat64(scale_x);
  return builder.offset();
}

}
