#!/usr/bin/env bash
# Build the WASM package into src/ts/, the directory npm publishes from.
#
# src/ts/ holds exactly one tracked file: package.json, carrying the npm
# name and version. Everything else there is generated by this script and
# gitignored, so a local build and a CI publish produce the same tree.
#
# Artifacts are copied individually ON PURPOSE. `cp -r pkg/*` also copies
# wasm-pack's own .gitignore (a single `*`) over src/ts/.gitignore, which
# is how generated files ended up committed in the first place.
#
# Usage: scripts/build_wasm.sh [--dev]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM_DIR="${REPO_ROOT}/src/rust/wasm"
OUT="${REPO_ROOT}/src/ts"

PROFILE="--release"
[[ "${1:-}" == "--dev" ]] && PROFILE="--dev"

command -v wasm-pack >/dev/null || {
  echo "wasm-pack not found; install it with: cargo install wasm-pack" >&2
  exit 1
}

# --no-pack: package.json is hand-maintained in src/ts, not generated.
# --target web: matches what the published package's `main` expects.
(cd "${WASM_DIR}" && wasm-pack build --target web --no-pack "${PROFILE}")

for f in fcb_wasm.js fcb_wasm.d.ts fcb_wasm_bg.wasm fcb_wasm_bg.wasm.d.ts; do
  cp "${WASM_DIR}/pkg/${f}" "${OUT}/${f}"
done

# wasm-bindgen emits snippets/ only when a binding uses inline JS. The
# package.json `sideEffects` entry refers to it, so carry it when present.
if [[ -d "${WASM_DIR}/pkg/snippets" ]]; then
  rm -rf "${OUT}/snippets"
  cp -r "${WASM_DIR}/pkg/snippets" "${OUT}/snippets"
fi

echo "WASM package built into ${OUT}"
