#!/usr/bin/env bash
# Regenerate the committed Python FlatBuffers bindings from src/fbs/*.fbs.
#
# flatc must be compatible with the `flatbuffers` pip runtime pinned in
# src/py/pyproject.toml -- generated code calls runtime APIs directly, and
# those APIs shift across versions.
# Generated with: flatc 25.9.23 / flatbuffers runtime >=24.3.25
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/src/py/flatcitybuf/generated"

EXPECTED_FLATC_VERSION="${FCB_FLATC_VERSION:-25.9.23}"
ACTUAL="$(flatc --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
if [[ "${ACTUAL}" != "${EXPECTED_FLATC_VERSION}" ]]; then
  echo "ERROR: flatc ${ACTUAL} found, but ${EXPECTED_FLATC_VERSION} is required." >&2
  echo "       It must match the flatbuffers Python runtime you target." >&2
  echo "       Override with FCB_FLATC_VERSION=<v> if you have bumped both." >&2
  exit 1
fi

rm -rf "${OUT}" && mkdir -p "${OUT}"
flatc --python --gen-onefile -o "${OUT}" -I "${REPO_ROOT}/src/fbs" \
  "${REPO_ROOT}/src/fbs/header.fbs" \
  "${REPO_ROOT}/src/fbs/feature.fbs" \
  "${REPO_ROOT}/src/fbs/geometry.fbs" \
  "${REPO_ROOT}/src/fbs/extension.fbs"

# __init__.py is generated (not hand-written) because this directory is
# rm -rf'd on every run: re-export every top-level class from every
# *_generated.py module flatc produced, sorted, so callers can write
# `flatcitybuf.generated.Header` etc. without knowing which schema file a
# given table/struct/enum came from. Kept in sync automatically as the
# .fbs schemas evolve.
INIT="${OUT}/__init__.py"
{
  echo "# Generated by scripts/gen_python_fbs.sh -- do not edit by hand."
  echo '"""Re-exports of the flatc-generated FlatCityBuf FlatBuffers bindings."""'
  echo "from __future__ import annotations"
  echo
  for f in "${OUT}"/*_generated.py; do
    grep -oE '^class [A-Za-z0-9_]+' "${f}" | awk '{print $2}'
  done | sort -u | while read -r cls; do
    module="$(grep -lE "^class ${cls}\\(" "${OUT}"/*_generated.py \
      | head -1 | xargs basename | sed 's/\.py$//')"
    echo "from .${module} import ${cls} as ${cls}"
  done
} > "${INIT}"

echo "Python bindings written to ${OUT}"
