# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatCityBuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GeographicalExtent(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 48

    # GeographicalExtent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GeographicalExtent
    def Min(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # GeographicalExtent
    def Max(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj


def CreateGeographicalExtent(builder, min_x, min_y, min_z, max_x, max_y, max_z):
    builder.Prep(8, 48)
    builder.Prep(8, 24)
    builder.PrependFloat64(max_z)
    builder.PrependFloat64(max_y)
    builder.PrependFloat64(max_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(min_z)
    builder.PrependFloat64(min_y)
    builder.PrependFloat64(min_x)
    return builder.Offset()
