# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatCityBuf

class GeometryType(object):
    MultiPoint = 0
    MultiLineString = 1
    MultiSurface = 2
    CompositeSurface = 3
    Solid = 4
    MultiSolid = 5
    CompositeSolid = 6
