/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_httpfcbreader_free: (a: number, b: number) => void;
export const __wbg_asyncfeatureiter_free: (a: number, b: number) => void;
export const httpfcbreader_new: (a: number, b: number) => any;
export const httpfcbreader_cityjson: (a: number) => [number, number, number];
export const httpfcbreader_meta: (a: number) => [number, number, number];
export const httpfcbreader_select_all: (a: number) => any;
export const httpfcbreader_select_spatial: (a: number, b: number) => any;
export const httpfcbreader_select_attr_query: (a: number, b: number) => any;
export const asyncfeatureiter_header: (a: number) => [number, number, number];
export const asyncfeatureiter_features_count: (a: number) => number;
export const asyncfeatureiter_next: (a: number) => any;
export const asyncfeatureiter_cur_cj_feature: (a: number) => [number, number, number];
export const __wbg_wasmspatialquery_free: (a: number, b: number) => void;
export const wasmspatialquery_new: (a: any) => [number, number, number];
export const wasmspatialquery_query_type: (a: number) => [number, number];
export const wasmspatialquery_min_x: (a: number) => [number, number];
export const wasmspatialquery_min_y: (a: number) => [number, number];
export const wasmspatialquery_max_x: (a: number) => [number, number];
export const wasmspatialquery_max_y: (a: number) => [number, number];
export const wasmspatialquery_x: (a: number) => [number, number];
export const wasmspatialquery_y: (a: number) => [number, number];
export const wasmspatialquery_to_js: (a: number) => any;
export const __wbg_wasmattrquery_free: (a: number, b: number) => void;
export const wasmattrquery_new: (a: any) => [number, number, number];
export const wasmattrquery_inner: (a: number) => any;
export const cjToObj: (a: any) => [number, number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure550_externref_shim: (a: number, b: number, c: any) => void;
export const closure589_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
