/*
 * 3DBAG API
 *
 * The [3DBAG](https://3dbag.nl) is an up-to-date dataset containing 3D building models of the Netherlands.  The 3DBAG is open data. It contains 3D models at multiple levels of detail,  which are generated by combining two open data sets:  the building data from the BAG and the height data from the AHN.  The 3DBAG is updated regularly, keeping it up-to-date with the latest openly  available building stock and elevation information.  The 3DBAG is maintained by the 3D geoinformation group and 3DGI.  Copyright (c) 2023 TU Delft 3D geoinformation group, Ravi Peters (3DGI), and Balázs Dukai (3DGI)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@3dbag.nl
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_feature_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFeatureIdError {
    Status400(models::Exception),
    Status404(models::Exception),
    Status500(models::Exception),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_features`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFeaturesError {
    Status400(models::Exception),
    Status404(models::Exception),
    Status500(models::Exception),
    UnknownValue(serde_json::Value),
}


/// Fetches a specific pand feature by it's featureId (ie. the BAG `identificatie` attribute). The feature is served in the CityJSONFeatures format and includes all Levels of Detail.
pub async fn get_feature_id(configuration: &configuration::Configuration, feature_id: &str, crs: Option<&str>) -> Result<models::FeatureCityJson, Error<GetFeatureIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_feature_id = feature_id;
    let p_crs = crs;

    let uri_str = format!("{}/collections/pand/items/{featureId}", configuration.base_path, featureId=crate::apis::urlencode(p_feature_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_crs {
        req_builder = req_builder.query(&[("crs", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FeatureCityJson`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FeatureCityJson`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFeatureIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch features from the 'pand' collection in CityJSONFeatures format.  The features includes all Levels of Detail.   To support access to larger collections without overloading the client, the API supports paged access with links to the next page, if more features are selected that the page size.  The `bbox` parameter can be used to select only a subset of the features in the collection (the features that are in the bounding box). The `bbox` parameter matches all features in the collection that are not associated with a location, too.  The `limit` and `offset` parameters may be used to control the subset of the selected features that should be returned in the response.
pub async fn get_features(configuration: &configuration::Configuration, limit: Option<i32>, offset: Option<i32>, bbox: Option<Vec<f64>>, crs: Option<&str>, bbox_crs: Option<&str>) -> Result<models::FeatureCollection, Error<GetFeaturesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_limit = limit;
    let p_offset = offset;
    let p_bbox = bbox;
    let p_crs = crs;
    let p_bbox_crs = bbox_crs;

    let uri_str = format!("{}/collections/pand/items", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_bbox {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("bbox".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("bbox", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_crs {
        req_builder = req_builder.query(&[("crs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_bbox_crs {
        req_builder = req_builder.query(&[("bbox-crs", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FeatureCollection`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FeatureCollection`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFeaturesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

